import 'package:memorie/models/stage.dart';

final List<MainStage> stages = [
  MainStage(
    id: '1',
    name: 'LIFE',
    subName: 'stage1',
    stageCardImage: 'lib/assets/backgrounds/stage1.png',
    gameStages: [
      GameStage(
        id: '1-1',
        name: 'Breakfast',
        subName: 'stage1-1',
        stageCardImage: 'lib/assets/backgrounds/stage1.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
        ],
        columnCount: 3,
      ),
      GameStage(
        id: '1-2',
        name: 'Lunch',
        subName: 'stage1-2',
        stageCardImage: 'lib/assets/backgrounds/stage1.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 3,
      ),
      GameStage(
        id: '1-3',
        name: 'Snack',
        subName: 'stage1-3',
        stageCardImage: 'lib/assets/backgrounds/stage1.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 3,
      ),
      GameStage(
        id: '1-4',
        name: 'Dinner',
        subName: 'stage1-4',
        stageCardImage: 'lib/assets/backgrounds/stage1.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
        ],
        columnCount: 3,
      ),
      GameStage(
        id: '1-5',
        name: 'Tea',
        subName: 'stage1-5',
        stageCardImage: 'lib/assets/backgrounds/stage1.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 3,
      ),
    ],
  ),
  MainStage(
    id: '2',
    name: 'Study',
    subName: 'stage2',
    stageCardImage: 'lib/assets/backgrounds/stage2.png',
    gameStages: [
      GameStage(
        id: '2-1',
        name: 'Learn',
        subName: 'stage2-1',
        stageCardImage: 'lib/assets/backgrounds/stage2.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 4,
      ),
      GameStage(
        id: '2-2',
        name: 'Education',
        subName: 'stage2-2',
        stageCardImage: 'lib/assets/backgrounds/stage2.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 4,
      ),
      GameStage(
        id: '2-3',
        name: 'Homework',
        subName: 'stage2-3',
        stageCardImage: 'lib/assets/backgrounds/stage2.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 2,
      ),
      GameStage(
        id: '2-4',
        name: 'Research',
        subName: 'stage2-4',
        stageCardImage: 'lib/assets/backgrounds/stage2.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
        ],
        columnCount: 4,
      ),
      GameStage(
        id: '2-5',
        name: 'Lecture',
        subName: 'stage2-5',
        stageCardImage: 'lib/assets/backgrounds/stage2.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
        ],
        columnCount: 4,
      ),
    ],
  ),
  MainStage(
    id: '3',
    name: 'Music',
    subName: 'stage3',
    stageCardImage: 'lib/assets/backgrounds/stage3.png',
    gameStages: [
      GameStage(
        id: '3-1',
        name: 'Melody',
        subName: 'stage3-1',
        stageCardImage: 'lib/assets/backgrounds/stage3.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 4,
      ),
      GameStage(
        id: '3-2',
        name: 'Rhythm',
        subName: 'stage3-2',
        stageCardImage: 'lib/assets/backgrounds/stage3.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
        ],
        columnCount: 5,
      ),
      GameStage(
        id: '3-3',
        name: 'Tempo',
        subName: 'stage3-3',
        stageCardImage: 'lib/assets/backgrounds/stage3.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
        ],
        columnCount: 5,
      ),
      GameStage(
        id: '3-4',
        name: 'Chord',
        subName: 'stage3-4',
        stageCardImage: 'lib/assets/backgrounds/stage3.png',
        gridItems: [
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
        ],
        columnCount: 3,
      ),
      GameStage(
        id: '3-5',
        name: 'Harmony',
        subName: 'stage3-5',
        stageCardImage: 'lib/assets/backgrounds/stage3.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 4,
      ),
    ],
  ),
  MainStage(
    id: '4',
    name: 'History',
    subName: 'stage4',
    stageCardImage: 'lib/assets/backgrounds/stage4.png',
    gameStages: [
      GameStage(
        id: '4-1',
        name: 'Civilization',
        subName: 'stage4-1',
        stageCardImage: 'lib/assets/backgrounds/stage4.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
        ],
        columnCount: 5,
      ),
      GameStage(
        id: '4-2',
        name: 'Revolution',
        subName: 'stage4-2',
        stageCardImage: 'lib/assets/backgrounds/stage4.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
        ],
        columnCount: 3,
      ),
      GameStage(
        id: '4-3',
        name: 'Era',
        subName: 'stage4-3',
        stageCardImage: 'lib/assets/backgrounds/stage4.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
        ],
        columnCount: 6,
      ),
      GameStage(
        id: '4-4',
        name: 'Chronology',
        subName: 'stage4-4',
        stageCardImage: 'lib/assets/backgrounds/stage4.png',
        gridItems: [],
        columnCount: 6,
      ),
      GameStage(
        id: '4-5',
        name: 'Epic',
        subName: 'stage4-5',
        stageCardImage: 'lib/assets/backgrounds/stage4.png',
        gridItems: [
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: true),
          GridItem(isViewGrid: false),
          GridItem(isViewGrid: false),
        ],
        columnCount: 6,
      ),
    ],
  ),
];
